server:
  port: 8081
  servlet:
    context-path: /commodity
spring:
  application:
    name: cjs-commodity-service
  datasource:
    url: jdbc:mysql://10.0.29.187:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://10.0.29.92:8761/eureka/,http://10.0.29.232:8761/eureka/
logging:
  file: ${spring.application.name}.log
